models.py
from diary import db

class YearPlan(db.Model):
    content = db.Column(db.Text(), nullable=True)
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

class MonthPlan(db.Model):
    content = db.Column(db.Text(), nullable=True)
    id = db.Column(db.String(), primary_key=True)

views/main_views.py
from flask import Blueprint, render_template
from models import YearPlan

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/templates/plan.html/')
def plan():
    year_list = YearPlan.query.order_by(YearPlan.id.asc())
    return render_template('plan.html', year_list=year_list)

@bp.route('/templates/memo.html/')
def memo():
    return render_template('memo.html')
@bp.route('/templates/diarypage_table.html/')
def diarypage():
    return render_template('diarypage_table.html')
@bp.route('/templates/board.html/')
def board():
    return render_template('board.html')

views/second_views.py
from flask import Blueprint, url_for, request
from werkzeug.utils import redirect
from datetime import datetime

from diary import db
from models import YearPlan

bp = Blueprint('year', __name__, url_prefix='/year')

@bp.route('/create/', methods=('POST','GET'))
def create():
    content = request.form['content']
    yp = YearPlan(content=content)
    db.session.add(yp)
    db.session.commit()
    return redirect(url_for('main.plan'))

templates/board.html
<!DOCTYPE html>
<html>
    <head>
        <title>dear my diary</title>

        <meta charset="UTF-8">
        <meta content="width=device-width", initial-scale="1.0">
        <link rel="stylesheet" href="../../static/css/mainpage.css">
        <link rel="stylesheet" href="../../static/css/calendar.css">
        <link rel="stylesheet" href="../../static/css/board.css">


		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap" rel="stylesheet">
    </head>


    <body>
        <header>
            <a href="../../"><img src="../../static/img/logo.png"></a>
        </header>

        <div id="mp">
            <div id = "lp">
                    <settings-cal>
                        <div class="container">
                            <div class="calendar">
                                <div class="month">
                                    <b class="go-prevmonth">&lt</b>
                                    <div class="date">
                                        <h1></h1>
                                        <p></p>
                                    </div>
                                    <b class="go-nextmonth">&gt</b>
                                </div><!--month-->
                                <div class="weekdays">
                                    <div>일</div>
                                    <div>월</div>
                                    <div>화</div>
                                    <div>수</div>
                                    <div>목</div>
                                    <div>금</div>
                                    <div>토</div>
                                </div>
                                <div class="days">

                                </div>
                            </div>
                        </div>

                        <script src="../../static/js/calendar.js"></script>
                    </settings-cal>


                <a href="../../templates/diarypage_table.html" class="list"><img src="../../static/img/diary1.png"></a>
                <a href="../../templates/plan.html" class="list"><img src="../../static/img/plan1.png" ></a>
                <a href="../../templates/memo.html" class="list"><img src="../../static/img/memo1.png"></a>
                <a href="../../templates/board.html" class="list"><img src="../../static/img/board1.png"></a>

                </div>


                <div id = "rp">
                    <div class="qdiv textcenter text15" id="qtitle">
                        <h1>공지사항</h1>
                    </div>
                    <div class="qdiv text2" id="qlist">
                        <ul>
                            <li><a href="#">2022.06.05 업데이트 내용안내</a></li>
                            <br><br><br>
                            <li><a href="#">2022.05.27 업데이트 내용안내</a></li>
                            <br><br><br>
                            <li><a href="#">2022.05.16 업데이트 내용안내</a></li>
                            <br><br><br>
                            <li><a href="#">2022.05.08 업데이트 내용안내</a></li>
                            <br><br><br>
                            <li><a href="#">2022.04.29 업데이트 내용안내</a></li>
                            <br><br><br>
                            <li><a href="#">2022.04.21 업데이트 내용안내</a></li>
                            <br><br><br>
                            <li><a href="#">이용 설명서</a></li>
                            <br><br><br>

                        </ul>
                    </div>
                </div>


                <div id = "bookmark">
                    <div class="hidden" >
                        <div class="bookmarker" style="background-color: #FA5858;">diary</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #FAAC58;">plan</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #E5D85C;">memo</div>
                    </div>
                    <div >
                        <div class="bookmarker" style="background-color: #B1DB4E;">board</div>
                    </div>



                </div>


        </div>
    </body>
</html>

templates/diarypage_table.html
<!DOCTYPE html>
<html lang="kr">
    <head>
        <title>dear my diary</title>

        <meta charset="UTF-8">
        <meta content="width=device-width", initial-scale="1.0">
        <link rel="stylesheet" href="../../static/css/mainpage.css">
		<link rel="stylesheet" href="../../static/css/calendar.css">
        <link rel="stylesheet" href="../../static/css/diarypage_table.css">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.6.0.js" ></script>

        	        
    </head>


    <body>   
        <header>
            <a href="../../"><img src="../../static/img/logo.png"></a>
        </header>

        <div id="mp"> 
            <div id = "lp">
                <settings-cal>
                    <div class="container">
                        <div class="calendar">
                            <div class="month">
                                <b class="go-prevmonth">&lt</b>
                                <div class="date">
                                    <h1></h1>
                                    <p></p>
                                </div>
                                <b class="go-nextmonth">&gt</b>
                            </div><!--month-->
                            <div class="weekdays">
                                <div>일</div>
                                <div>월</div>
                                <div>화</div>
                                <div>수</div>
                                <div>목</div>
                                <div>금</div>
                                <div>토</div>
                            </div>
                            <div class="days">
                                
                            </div>
                        </div>
                    </div>
            
                    <script src="../../static/js/calendar.js"></script>
                </settings-cal>                
                
                <a href="../../templates/diarypage_table.html" class="list"><img src="../../static/img/diary1.png"></a>
                <a href="../../templates/plan.html" class="list"><img src="../../static/img/plan1.png" ></a>
                <a href="../../templates/memo.html" class="list"><img src="../../static/img/memo1.png"></a>
                <a href="../../templates/board.html" class="list"><img src="../../static/img/board1.png"></a>

                </div>
            
            
                <div id = "rp">
                    <div class="weekly_header">
                        <div class="weekly_nav">
                            <b class="go-prevweek">&lt</b>
                            <div class="date2">
                                <p></p>
                            </div>
                            <b class="go-nextweek">&gt</b>
                        </div>   
                    </div>

                    <div class="weekly_main">
                        <table border="1">
                            <thead>
                                <tr class="weekly_days">
                                    <th class="weekly_day">일</th>
                                    <th class="weekly_day">월</th>
                                    <th class="weekly_day">화</th>
                                    <th class="weekly_day">수</th>
                                    <th class="weekly_day">목</th>
                                    <th class="weekly_day">금</th>
                                    <th class="weekly_day">토</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="todolist" id="calendar">

                                </tr>
                                <form>
                                    <tr class="todo" ></tr>
                                </form>
                                
                                   
                                <tr class="diarys">
                                    <!--
                                    <td><button class="diarybtn wh100">diary</button></td>
                                    
                                    -->
                                </tr>
                            </tbody>
                            
                        </table>

                        <br>

                        


                            
                                <div><b>매일 할 일</b></div>
                                <br>
                            
                                <td  class="todolabel">
                                    <div>
                                        <form class="todo-form">
                                            <input type="text" class="todo-input" placeholder="매일 할 일을 입력하세요">
                                            <button type="submit" class="add-button todolabelplus">+</button>
                                          </form>
                                        <ul class="todo-items">
                                            
                                          </ul>
                                    </div>
                                                                       
                                
                        <script src="../../static/js/todoplan.js"></script>
                            
                    </div>

                       
                </div>
                

                
                <div id = "bookmark">
                    <div >
                        <div class="bookmarker" style="background-color: #FA5858;">diary</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #FAAC58;">plan</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #E5D85C;">memo</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #B1DB4E;">board</div>
                    </div>

                    
                    
                </div>
            

        </div>
        <!--
        <script src="diarypage.js" defer></script>
        --> 
        <script src="../../static/js/todo.js"></script>
        
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>dear my diary</title>

        <meta charset="UTF-8">
        <meta content="width=device-width", initial-scale="1.0">
        <link rel="stylesheet" href="static/css/mainpage.css">
        <link rel="stylesheet" href="static/css/calendar.css">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap" rel="stylesheet">
        <style>
            #rimg { width:100%; height: 100%; }
        </style>
    </head>


    <body>
        <header>
            <img src="static/img/logo.png">
        </header>

        <div id="mp">
            <div id = "lp">
                    <settings-cal>
                        <div class="container">
                            <div class="calendar">
                                <div class="month">
                                    <b class="go-prevmonth">&lt</b>
                                    <div class="date">
                                        <h1></h1>
                                        <p></p>
                                    </div>
                                    <b class="go-nextmonth">&gt</b>
                                </div><!--month-->
                                <div class="weekdays">
                                    <div>일</div>
                                    <div>월</div>
                                    <div>화</div>
                                    <div>수</div>
                                    <div>목</div>
                                    <div>금</div>
                                    <div>토</div>
                                </div>
                                <div class="days">

                                </div>
                            </div>
                        </div>

                        <script src="static/js/calendar.js"></script>
                    </settings-cal>

                <a href="../templates/diarypage_table.html" class="list"><img src="../static/img/diary1.png"></a>
                <a href="../templates/plan.html" class="list"><img src="../static/img/plan1.png" ></a>
                <a href="../templates/memo.html" class="list"><img src="../static/img/memo1.png"></a>
                <a href="../templates/board.html" class="list"><img src="../static/img/board1.png"></a>

                </div>


                <div class="rp">
                    <!--사이트 내용 들어갈 부분
                        ex) planpage.html,planpage.css 따로 저장-->
                    <img id="rimg" src="static/img/quokka.jpg">
                </div>


                <div id = "bookmark">
                    <div >
                        <div class="bookmarker" style="background-color: #FA5858;">diary</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #FAAC58;">plan</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #E5D85C;">memo</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #B1DB4E;">board</div>
                    </div>



                </div>


        </div>

</html>

templates/plan.html
<!DOCTYPE html>
<html>
    <head>
        <title>dear my diary</title>

        <meta charset="UTF-8">
        <meta content="width=device-width", initial-scale="1.0">
        <link rel="stylesheet" href="../../static/css/mainpage.css">
        <link rel="stylesheet" href="../../static/css/calendar.css">
        <link rel="stylesheet" href="../../static/css/plan.css">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap" rel="stylesheet">
    </head>


    <body>
        <header>
            <a href="../../"><img src="../../static/img/logo.png"></a>
        </header>

        <div id="mp">
            <div id = "lp">
                    <settings-cal>
                        <div class="container">
                            <div class="calendar">
                                <div class="month">
                                    <b class="go-prevmonth">&lt</b>
                                    <div class="date">
                                        <h1></h1>
                                        <p></p>
                                    </div>
                                    <b class="go-nextmonth">&gt</b>
                                </div><!--month-->
                                <div class="weekdays">
                                    <div>일</div>
                                    <div>월</div>
                                    <div>화</div>
                                    <div>수</div>
                                    <div>목</div>
                                    <div>금</div>
                                    <div>토</div>
                                </div>
                                <div class="days">

                                </div>
                            </div>
                        </div>

                        <script src="../../static/js/calendar.js"></script>
                    </settings-cal>


               <a href="../../templates/diarypage_table.html" class="list"><img src="../../static/img/diary1.png"></a>
                <a href="../../templates/plan.html" class="list"><img src="../../static/img/plan1.png" ></a>
                <a href="../../templates/memo.html" class="list"><img src="../../static/img/memo1.png"></a>
                <a href="../../templates/board.html" class="list"><img src="../../static/img/board1.png"></a>

                </div>


                <div id = "rp">
                    <!--사이트 내용 들어갈 부분
                        ex) planpage.html,planpage.css 따로 저장-->
                    {% block content %}
                     <div id = "annual_plan_collection">
                            <h2><u>연간계획</u></h2>
                            <form method="post" action="{{ url_for('year.create') }}">
                                <textarea style='resize : none;' id = "text" name="content" cols = "41" rows = "39">{% for yl in year_list %}{{ yl.content }}{% endfor %}</textarea>
                                <input type="submit" value="저장">
                            </form>
                        </div>

                        <div id = "monthly_plan_collection">
                            <form>
                                <table>
                                    <tbody>
                                        <tr>
                                            <td><h4>1 JAN</h4></td>
                                            <td><h4>2 FEB</h4></td>
                                            <td><h4>3 MAR</h4></td>
                                        </tr>
                                        <tr>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                         </tr>
                                         <tr>
                                            <td><h4>4 APR</h4></td>
                                            <td><h4>5 MAY</h4></td>
                                            <td><h4>6 JUN</h4></td>
                                        </tr>
                                         <tr>
                                            <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                         </tr>
                                         <tr>
                                            <td><h4>7 JUL</h4></td>
                                            <td><h4>8 AUG</h4</td>
                                            <td><h4>9 SEP</h4></td>
                                        </tr>
                                         <tr>
                                            <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                        </tr>
                                        <tr>
                                            <td><h4>10 OCT</h4></td>
                                            <td><h4>11 NOV</h4></td>
                                            <td><h4>12 DEC</h4></td>
                                        </tr>
                                        <tr>
                                            <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                             <td ><textarea rows = "6" wrap="hard"></textarea></td>
                                        </tr>
                                        <td><input type="submit" value="저장"></td>
                                     </tbody>
                                 </table>
                            </form>
                        </div>
                </span>
                {% endblock %}
                </div>


                <div id = "bookmark">
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #FA5858;">diary</div>
                    </div>
                    <div>
                        <div class="bookmarker" style="background-color: #FAAC58;">plan</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #E5D85C;">memo</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #B1DB4E;">board</div>
                    </div>



                </div>


        </div>

</html>

templates/profile.html
<!DOCTYPE html>
<html>
    <head>
        <title>profile</title>

        <meta charset="UTF-8">
        <meta content="width=device-width", initial-scale="1.0">
        <link rel="stylesheet" href="../mainpage.css">
		<link rel="stylesheet" href="../calendar.css">
        <link rel="stylesheet" href="profile.css">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap" rel="stylesheet">	        
    </head>


    <body>   
        <header>
            <img src="../imgs/로고.png">
        </header>

        <div id="mp"> 
            <div id = "lp">
                <settings-cal>
                    <div class="container">
                        <div class="calendar">
                            <div class="month">
                                <b class="go-prevmonth">&lt</b>
                                <div class="date">
                                    <h1></h1>
                                    <p></p>
                                </div>
                                <b class="go-nextmonth">&gt</b>
                            </div><!--month-->
                            <div class="weekdays">
                                <div>일</div>
                                <div>월</div>
                                <div>화</div>
                                <div>수</div>
                                <div>목</div>
                                <div>금</div>
                                <div>토</div>
                            </div>
                            <div class="days">
                                
                            </div>
                        </div>
                    </div>
            
                    <script src="../calendar.js"></script>                        
                </settings-cal>                
                
                <a href="../diary_page/diarypage_table.html" class="list"><img src="../imgs/diary1.png"></a>
                <a href="../plan_page/plan.html" class="list"><img src="../imgs/plan1.png" ></a>
                <a href="../memo_page/memo.html" class="list"><img src="../imgs/memo1.png"></a>
                <a href="../board_page/인증게시판.html" class="list"><img src="../imgs/board1.png"></a>
                <a href="#" class="list"><img src="../imgs/profile1.png"></a>

                </div>
            
            <div>
                <span id = "rp">
                    <div class="img-box">
                        <img src="../imgs/profileimg.png" class = 'pf'>
                    </div>
                    <div class="name-box">
                        <h2>사용자명</h2>
                    </div>
                    <div class="content">
                        <div class="logout"><strong>&rtrif;로그아웃</strong></div>
                        <div class="account_settings"><strong>&rtrif;계정 설정</strong></div>
                        <div class="my_writings"><strong>&rtrif;내가 쓴 글</strong></div>
                        <div class="cover_decoration"><strong>&rtrif;표지 꾸미기</strong></div>
                    </div>

                    
                </span>

                
                <span id = "bookmark">
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #FA5858;">diary</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #FAAC58;">plan</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #E5D85C;">memo</div>
                    </div>
                    <div class="hidden">
                        <div class="bookmarker" style="background-color: #B1DB4E;">board</div>
                    </div>
                    <div >
                        <div class="bookmarker" style="background-color: #79ABFF;">profile</div>
                    </div>
                    
                    
                </span>
            </div>

        </div>

</html>